title: Data Analyst | Fraud Risk & Financial Analytics
theme: minima

github_url: https://github.com/samplerittgithub
linkedin_url: https://www.linkedin.com/in/http://www.linkedin.com/in/jegan-d-a57a80236/
cv_url: /assets/Jeganathan_Duraisamy_CV.pdf
location: UK
tagline: UK • Python • SQL • AWS • Power BI
