theme: minima

github_url: https://github.com/samplerittgithub
linkedin_url: https://www.linkedin.com/in/jeganathan-d-a57a80236
cv_url: /assets/Jeganathan%20Duraisamy_Data%20Analyst.pdf
location: UK
tagline: UK • Python • SQL • AWS • Power BI
